apiVersion: v1
description: Bookinfo Productpage Service Helm Chart
name: bookinfo-productpage
version: 1.0.0
appVersion: 1.0.0
home: http://itkmitl.bookinfo.dev.opsta.net/student36/productpage
maintainers:
  - name: student36
    email: 62070184@it.kmitl.ac.th
sources:
  - https://github.com/loukhin/itkmitl-bookinfo-productpage
